site_name: Fiware-Docker-Container-Service
site_url: https://fiware-docker-container-service.readthedocs.org
repo_url: https://github.com/fiware-docker/docker-container-service.git
site_description: FIWARE Simple Docker Hosting Documentation
docs_dir: docs
site_dir: html
markdown_extensions: [toc,fenced_code]
use_directory_urls: false
theme: readthedocs
extra_css: ["https://fiware.org/style/fiware_readthedocs.css"]
pages:
  - 'Home': 'index.md'
  - 'FDCS Installation & Administration Manual': 'adminguide/admin-guide.md'
  - 'FDCS User & Programmers Manual': 'userguide/user-guide.md'

